### ISSUE TITLE
AWS cloud plots

### ISSUE THREAD

**Issue by dalamascus** [BrianHaak/cloud-plot#1]
Hi BrianHaak,

i deployed it. To be honest the invoices I am receiving from AWS are way to high to proceed.. 👎  Need to find another way to earn some money to pay the AWS invoices...

**Comment by t0mZ4** [comment]
What does it cost you per plot then?

**Comment by BrianHaak** [comment]
From the Read Me:

"Do you own research before deploying this project.
This project is mostly untested. It is intended for educational purposes only.
Use at your own risk and expense."
